### ISSUE TITLE
Error loading plugin: TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by sindreruud** [voigtjr/rkbeets#2]
Hi!

This project looks really cool and fits exactly what I am looking for. Just tried giving this a quick test now, but loading the plugin gives an error:

```
root@beets-test:~ # beet version
** error loading plugin rkbeets:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python3.9/site-packages/beetsplug/rkbeets/__init__.py", line 55, in <module>
    class DimensionsDB():
  File "/usr/local/lib/python3.9/site-packages/beetsplug/rkbeets/__init__.py", line 68, in DimensionsDB
    def __init__(self, csv_path: Path | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

beets version 1.6.0
Python version 3.9.18
```

Installed rkbeets with `pip install git+https://github.com/voigtjr/rkbeets`

Any suggestions on how to fix this?

**Comment by voigtjr** [comment]
Hi! I was busy all week, I haven't worked on this in a few months, I will take a look this weekend.

Off the top of my head, looks like you are working as root, this isn't usually a good idea. 

This project is a work in progress, I recommend installing from source, detailed [here](https://github.com/voigtjr/rkbeets#installation), let me know if you have questions about that.

**Comment by sindreruud** [comment]
Thank you for putting in the time :) 

And as for root, it is indeed. This is in a virtual environment with test data just to give this a spin. And `pip install git+repo` installs from source, as far as I know. I just find it a bit faster and easier. 
If I put this into "production" I'll set it up more securely.

**Comment by voigtjr** [comment]
Finally working on this, I was able to reproduce the issue, working on a fix.

**Comment by voigtjr** [comment]
So the problem is that 3.9 doesn't support the `A | B` syntax instead of `Union[A, B]`, [this was added in 3.10](https://peps.python.org/pep-0604/). I did a quick audit and this is a nontrivial backwards change. Fixing that function isn't bad, it becomes:

`def __init__(self, csv_path: Union[Path, None] = None):`

but there are other monstrosities in the project that I don't have time to address right now, such as this one 😬:

    def get_export_conversion_info(
        self
    ) -> tuple[list[str], tuple[str, str, Callable[[Any], Any] | None]]:

_These should probably be refactored to eliminate the need for the union_

Is there any chance you can use Python 3.10?
